### ISSUE TITLE
Fix profiler panel view expandable data

### ISSUE THREAD

**Issue by Algatux** [facile-it/mongodb-bundle#15]
All expandable data on the profiler panel suffers of click problems.

we must add a little button to expand/collapse the data, removing the click event from the text

a little javascript refactoring will be apreciated :smile:

**Comment by Jean85** [comment]
Do we have any other SF toolbar component that does something similar? Maybe we can copy the behavior for consistency?

**Comment by Algatux** [comment]
Doctrine does a similar thing but uses ajax calls (because of the explain execution).
We do not need that mechanism because our needing is only to format/toggle the json string

**Comment by Jean85** [comment]
Oh ok. We can copy at least the UI?

**Comment by Algatux** [comment]
The ui is part of symfony web profiler.
