### ISSUE TITLE
Deprecated ReadPreference::getMode

### ISSUE THREAD

**Issue by Vegeeto** [facile-it/mongodb-bundle#185]
According to the official documentation, the getMode() has been deprecated and will be removed in version 2.0 of MongoDB extension.

Usage on file _src/Capsule/Collection.php_, method `translateReadPreference` (line 210)

I suggest refactor translateReadPreference method to the following one:
```
    private function readPreferenceMode(ReadPreference $readPreference): string
    {
        return $readPreference->getModeString();
    }
```

Reference: https://www.php.net/manual/es/mongodb-driver-readpreference.getmode.php

**Comment by Jean85** [comment]
Note: `getModeString()` is present since 1.7.0, so this would need a slight bump to the `ext-mongodb` requirement: https://www.php.net/manual/en/mongodb-driver-readpreference.getmodestring.php
