### ISSUE TITLE
Removing phpunit dev dependency

### ISSUE THREAD

**Issue by Algatux** [facile-it/mongodb-bundle#3]
Removing phpunit from dev dependency avoids production dependency issues, just for example a lot of bundle projects do not include it for the same reason

es.
https://github.com/symfony/symfony/blob/master/composer.json#L78
https://github.com/symfony/framework-bundle/blob/master/composer.json#L40
https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/composer.json#L29
https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/composer.json#L34
https://github.com/sonata-project/SonataAdminBundle/blob/3.x/composer.json#L45
https://github.com/sonata-project/SonataCoreBundle/blob/3.x/composer.json#L29

Another reason is to not forse the contributor to local install it if he prefers to have it in phar form or globally installed.

IMHO we must remove it

**Comment by Jean85** [comment]
I see.
I think also that this impedes the local development of the bundle. Maybe we can avoid these issues adding a prepared docker env where, for example, PHPUnit (and other requirements, like the mongo ext) is installed?

**Comment by Algatux** [comment]
We have a "wrapper" library that needs only unit tests, I don't now if an entire docker environment will be usefull only to supply the extension, we can bypass the composer install problem ignoring the platform reqs.
About phpunit we can use a global install or the phar archive like I did during the initial development.
