### ISSUE TITLE
[SF4] Deprecations about command auto-registration

### ISSUE THREAD

**Issue by Jean85** [facile-it/mongodb-bundle#48]
I'm trying to remove all the deprecation from my Symfony 3.4 app, and I'm receiving those from this bundle:
> Auto-registration of the command "Facile\MongoDbBundle\Command\DropCollectionCommand" is deprecated since Symfony 3.4 and won't be supported in 4.0. Use PSR-4 based service discovery instead: 2x
> ...
>
> Auto-registration of the command "Facile\MongoDbBundle\Command\LoadFixturesCommand" is deprecated since Symfony 3.4 and won't be supported in 4.0. Use PSR-4 based service discovery instead: 2x
> ...
>
> Auto-registration of the command "Facile\MongoDbBundle\Command\DropDatabaseCommand" is deprecated since Symfony 3.4 and won't be supported in 4.0. Use PSR-4 based service discovery instead: 2x
> ...

**Comment by Algatux** [comment]
closed #49
