### ISSUE TITLE
Installing with Symfony4 returns errors

### ISSUE THREAD

**Issue by Dameon87** [facile-it/mongodb-bundle#52]
Writing lock file
Generating autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
Symfony operations: 1 recipe (7f646d045a30af20e1fa82f9cb3b3c48)
  - Configuring facile-it/mongodb-bundle (>=0.6.4): From auto-generated recipe
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!
!!  In ArrayNode.php line 238:
!!
!!    The child node "clients" at path "mongo_db_bundle" must be configured.
!!
!!
!!

Installation failed, reverting ./composer.json to its original content.

You can get by this error by putting a default configuration file (as in the README) in config/packages/mongo_db_bundle.yaml
This fixes the error, but requires manual work before installing the bundle.

**Comment by Algatux** [comment]
@Dameon87 thanks for reporting this issue

**Comment by Jean85** [comment]
This would be easily solved with a Symfony Flex contrib recipe, where a basic YAML config is enabled with default values, like a connection to localhost with the default port and no auth.

This would be enough to let the app load without issues, and throw an error only if the DB is accessed without the right config.

**Comment by Dameon87** [comment]
That would definitely work! I've yet to tinker with the Flex recipes, however.

**Comment by Algatux** [comment]
@Dameon87 the flex recipe has been accepted can I close this issue ?
