### ISSUE TITLE
ContainerAwareCommand class is deprecated

### ISSUE THREAD

**Issue by Jean85** [facile-it/mongodb-bundle#73]
I'm updating my app to Symfony 4.2, and this deprecation popped up during fixture loading:

> The "Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand" class is deprecated since Symfony 4.2, use "Symfony\Component\Console\Command\Command" w
ith dependency injection instead.

We should migrate the `LoadFixturesCommand` (and others) to direct dependency injection.

**Comment by ilario-pierbattista** [comment]
@Jean85 There I've added a CI job with deprecation warning (allowed to fail).

Also I've pushed the branch `1905_fix_symfony4_deprecations` with a simple fix (hoping that it will work) for twig deprecations). You can start from it if you want to help.

**Comment by Jean85** [comment]
Unfortunately your fix breaks BC. I've done something similar in #74, and I need to address one last deprecation too.

**Comment by ilario-pierbattista** [comment]
Thanks, I'm closing it in favour of #74
