### ISSUE TITLE
Allow to use the profiler in other environment than dev only

### ISSUE THREAD

**Issue by djgxp** [facile-it/mongodb-bundle#82]
In the config file, be able to allow multiple environment to use the profiler because it seems that currently only dev is allowed.

**Comment by ilario-pierbattista** [comment]
This shouldn't be a responsibility of the configuration of the bundle.
Your environments should be configured with a properly debug flag and a set of bundle to use.

**Comment by djgxp** [comment]
I totally agree with that !
it's just that I've got a "qa" environment from where I've got the debug toolbar working but without the mongodb view. The same in my "dev" environment work perfectly.
So for me currently it doesn't rely on the APP_DEBUG in you code but more on that portion of code:

```
# src/Services/ClientRegistry.php

private function buildClient(string $clientName, string $uri, array $options, array $driverOptions): Client
    {
        if ('dev' === $this->environment) {
            return new BundleClient($uri, $options, $driverOptions, $clientName, $this->eventDispatcher);
        }
        return new Client($uri, $options, $driverOptions);
    }
```

**Comment by ilario-pierbattista** [comment]
You're right! Our fault.

Would you like to write a test about that and propose a solution?

Thanks

**Comment by djgxp** [comment]
Here is what I've done one my fork:
https://github.com/facile-it/mongodb-bundle/pull/83/files

**Comment by ilario-pierbattista** [comment]
Discussion can goes on in #84
