### ISSUE TITLE
Add SSL certification files path in the configuration

### ISSUE THREAD

**Issue by antoniojlm84** [facile-it/mongodb-bundle#85]
Hi

I would like to connect to a mongo under ssl security with a SSL Certificate file.

As in php docs you can see:

https://www.php.net/manual/es/mongo.connecting.ssl.php

There is any solution in the bundle I'm missing? or maybe you could add this configuration feature to the bundle?.

Thanks in advance.

**Comment by ilario-pierbattista** [comment]
Hi, 
currently the bundle doesn't provide any solution for what you're asking.

Feel free to contribute if you're interested in it.

Ps: I'm refering to the english version of your link https://www.php.net/manual/en/mongo.connecting.ssl.php

**Comment by antoniojlm84** [comment]
How I can do a branch to upload my pull-request? I tried to push but I have a 403.

**Comment by ilario-pierbattista** [comment]
I suggest you to read https://help.github.com/en/articles/creating-a-pull-request

**Comment by Jean85** [comment]
@antoniojlm84 mind that you're referring to the wrong extension, the legacy one, `ext-mongo`. This bundle is for the newer one, `ext-mongodb`: https://www.php.net/manual/en/set.mongodb.php

**Comment by ilario-pierbattista** [comment]
#89 is merged, I'm closing this.
